services:
  user-service-db:
    image: postgres:16
    container_name: user-service-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: ..
      dockerfile: user-service/Dockerfile
    image: user-service:latest
    container_name: user-service
    depends_on:
      - user-service-db
    env_file:
      - .env.dev
    environment:
      DB_HOST: user-service-db
      DB_PORT: 5432
      SERVER_PORT: 8080

    ports:
      - "8080:8080"

volumes:
  pgdata:
